feat: QPPA-7012 bash script

diff --git a/scripts/measures/update-measures b/scripts/measures/update-measures
--- a/scripts/measures/update-measures
+++ b/scripts/measures/update-measures
@@ -5,6 +5,15 @@ maxPerformanceYear=2023
 
 Red='\033[0;31m'
 Green='\033[0;32m'
+bold=$(tput bold)
+
+# checks the exit code of the last command and exits if not successful code 0.
+function exitIfFailure () {
+  if (( $? != 0 )); then
+    echo -e "${Red}\n${bold}Update failed."
+    exit
+  fi
+}
 
 # This script is not made to work for years prior to 2023.
 if (( $currentPerformanceYear >= 2023 )) && (( $currentPerformanceYear <= $maxPerformanceYear )); then
@@ -15,27 +24,32 @@ if (( $currentPerformanceYear >= 2023 )) && (( $currentPerformanceYear <= $maxPe
   # Update the measures-data, if there are any updates:
   node dist/measures/$currentPerformanceYear/update-measures.js \
     $currentPerformanceYear
+  exitIfFailure
 
   echo -e "Ingesting the Spec Urls, if those files exist..."
   node dist/measures/$currentPerformanceYear/ingest-specifications-links.js \
     $currentPerformanceYear
+  exitIfFailure
   
   echo -e "Ingesting Quality and QCDR strata..."
   node dist/measures/$currentPerformanceYear/ingest-strata.js \
     $currentPerformanceYear \
     util/measures/$currentPerformanceYear/qcdr-strata.csv
-  
+  exitIfFailure
+
   node dist/measures/$currentPerformanceYear/ingest-strata.js \
     $currentPerformanceYear \
     util/measures/$currentPerformanceYear/quality-strata.csv
+  exitIfFailure
 
   echo -e "Validating new measures-data.json..."
   cat measures/$currentPerformanceYear/measures-data.json | \
 	node scripts/validate-data.js measures $currentPerformanceYear
+  exitIfFailure
   
-  echo -e "${Green}Update complete."
+  echo -e "${Green}\n${bold}Update complete."
   exit
 
 else
-  echo -e "${Red}Performance year ${currentPerformanceYear} not valid!"
+  echo -e "${Red}${bold}Performance year ${currentPerformanceYear} not valid."
 fi
